# Generated by Django 2.2.16 on 2020-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
